package com.clt.intel.bean;

import java.io.Serializable;
import java.util.Date;

public class System implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.system_id
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private Long systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.sys_name
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String sysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.sys_url
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String sysUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.sys_memo
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String sysMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.c_date
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private Date cDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.c_accout
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String cAccout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.u_date
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private Date uDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.u_account
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String uAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.status
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private Long status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.comp_name
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String compName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.comp_legal_person
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String compLegalPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.comp_pic
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String compPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.comp_pasw
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String compPasw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.comp_email
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String compEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.sys_pic
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String sysPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.sys_title
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String sysTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.appid
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.app_sec
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String appSec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_system.app_token
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String appToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table intel_system
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.system_id
     *
     * @return the value of intel_system.system_id
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public Long getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.system_id
     *
     * @param systemId the value for intel_system.system_id
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.sys_name
     *
     * @return the value of intel_system.sys_name
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.sys_name
     *
     * @param sysName the value for intel_system.sys_name
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setSysName(String sysName) {
        this.sysName = sysName == null ? null : sysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.sys_url
     *
     * @return the value of intel_system.sys_url
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getSysUrl() {
        return sysUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.sys_url
     *
     * @param sysUrl the value for intel_system.sys_url
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setSysUrl(String sysUrl) {
        this.sysUrl = sysUrl == null ? null : sysUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.sys_memo
     *
     * @return the value of intel_system.sys_memo
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getSysMemo() {
        return sysMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.sys_memo
     *
     * @param sysMemo the value for intel_system.sys_memo
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setSysMemo(String sysMemo) {
        this.sysMemo = sysMemo == null ? null : sysMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.c_date
     *
     * @return the value of intel_system.c_date
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public Date getcDate() {
        return cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.c_date
     *
     * @param cDate the value for intel_system.c_date
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setcDate(Date cDate) {
        this.cDate = cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.c_accout
     *
     * @return the value of intel_system.c_accout
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getcAccout() {
        return cAccout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.c_accout
     *
     * @param cAccout the value for intel_system.c_accout
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setcAccout(String cAccout) {
        this.cAccout = cAccout == null ? null : cAccout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.u_date
     *
     * @return the value of intel_system.u_date
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public Date getuDate() {
        return uDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.u_date
     *
     * @param uDate the value for intel_system.u_date
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setuDate(Date uDate) {
        this.uDate = uDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.u_account
     *
     * @return the value of intel_system.u_account
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getuAccount() {
        return uAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.u_account
     *
     * @param uAccount the value for intel_system.u_account
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setuAccount(String uAccount) {
        this.uAccount = uAccount == null ? null : uAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.status
     *
     * @return the value of intel_system.status
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.status
     *
     * @param status the value for intel_system.status
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.comp_name
     *
     * @return the value of intel_system.comp_name
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getCompName() {
        return compName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.comp_name
     *
     * @param compName the value for intel_system.comp_name
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setCompName(String compName) {
        this.compName = compName == null ? null : compName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.comp_legal_person
     *
     * @return the value of intel_system.comp_legal_person
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getCompLegalPerson() {
        return compLegalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.comp_legal_person
     *
     * @param compLegalPerson the value for intel_system.comp_legal_person
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setCompLegalPerson(String compLegalPerson) {
        this.compLegalPerson = compLegalPerson == null ? null : compLegalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.comp_pic
     *
     * @return the value of intel_system.comp_pic
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getCompPic() {
        return compPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.comp_pic
     *
     * @param compPic the value for intel_system.comp_pic
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setCompPic(String compPic) {
        this.compPic = compPic == null ? null : compPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.comp_pasw
     *
     * @return the value of intel_system.comp_pasw
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getCompPasw() {
        return compPasw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.comp_pasw
     *
     * @param compPasw the value for intel_system.comp_pasw
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setCompPasw(String compPasw) {
        this.compPasw = compPasw == null ? null : compPasw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.comp_email
     *
     * @return the value of intel_system.comp_email
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getCompEmail() {
        return compEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.comp_email
     *
     * @param compEmail the value for intel_system.comp_email
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setCompEmail(String compEmail) {
        this.compEmail = compEmail == null ? null : compEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.sys_pic
     *
     * @return the value of intel_system.sys_pic
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getSysPic() {
        return sysPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.sys_pic
     *
     * @param sysPic the value for intel_system.sys_pic
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setSysPic(String sysPic) {
        this.sysPic = sysPic == null ? null : sysPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.sys_title
     *
     * @return the value of intel_system.sys_title
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getSysTitle() {
        return sysTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.sys_title
     *
     * @param sysTitle the value for intel_system.sys_title
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setSysTitle(String sysTitle) {
        this.sysTitle = sysTitle == null ? null : sysTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.appid
     *
     * @return the value of intel_system.appid
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.appid
     *
     * @param appid the value for intel_system.appid
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.app_sec
     *
     * @return the value of intel_system.app_sec
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getAppSec() {
        return appSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.app_sec
     *
     * @param appSec the value for intel_system.app_sec
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setAppSec(String appSec) {
        this.appSec = appSec == null ? null : appSec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_system.app_token
     *
     * @return the value of intel_system.app_token
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getAppToken() {
        return appToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_system.app_token
     *
     * @param appToken the value for intel_system.app_token
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setAppToken(String appToken) {
        this.appToken = appToken == null ? null : appToken.trim();
    }
}