package com.clt.intel.bean;

import java.io.Serializable;
import java.util.Date;

public class UserSystem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_user_system.system_id
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private Long systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_user_system.user_id
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_user_system.c_date
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private Date cDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_user_system.c_accout
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String cAccout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_user_system.u_date
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private Date uDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_user_system.u_accout
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String uAccout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intel_user_system.user_openID
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private String userOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table intel_user_system
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_user_system.system_id
     *
     * @return the value of intel_user_system.system_id
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public Long getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_user_system.system_id
     *
     * @param systemId the value for intel_user_system.system_id
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_user_system.user_id
     *
     * @return the value of intel_user_system.user_id
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_user_system.user_id
     *
     * @param userId the value for intel_user_system.user_id
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_user_system.c_date
     *
     * @return the value of intel_user_system.c_date
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public Date getcDate() {
        return cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_user_system.c_date
     *
     * @param cDate the value for intel_user_system.c_date
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setcDate(Date cDate) {
        this.cDate = cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_user_system.c_accout
     *
     * @return the value of intel_user_system.c_accout
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getcAccout() {
        return cAccout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_user_system.c_accout
     *
     * @param cAccout the value for intel_user_system.c_accout
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setcAccout(String cAccout) {
        this.cAccout = cAccout == null ? null : cAccout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_user_system.u_date
     *
     * @return the value of intel_user_system.u_date
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public Date getuDate() {
        return uDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_user_system.u_date
     *
     * @param uDate the value for intel_user_system.u_date
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setuDate(Date uDate) {
        this.uDate = uDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_user_system.u_accout
     *
     * @return the value of intel_user_system.u_accout
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getuAccout() {
        return uAccout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_user_system.u_accout
     *
     * @param uAccout the value for intel_user_system.u_accout
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setuAccout(String uAccout) {
        this.uAccout = uAccout == null ? null : uAccout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intel_user_system.user_openID
     *
     * @return the value of intel_user_system.user_openID
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public String getUserOpenid() {
        return userOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intel_user_system.user_openID
     *
     * @param userOpenid the value for intel_user_system.user_openID
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    public void setUserOpenid(String userOpenid) {
        this.userOpenid = userOpenid == null ? null : userOpenid.trim();
    }
}