package com.clt.intel.dao;

import com.clt.intel.bean.System;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository("systemMapper")
public interface SystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intel_system
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    int deleteByPrimaryKey(Long systemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intel_system
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    int insert(System record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intel_system
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    int insertSelective(System record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intel_system
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    System selectByPrimaryKey(Long systemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intel_system
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    int updateByPrimaryKeySelective(System record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intel_system
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    int updateByPrimaryKey(System record);


    /**
     * 根据条件获取系统信息
     * @param system
     * @return
     */
    List<System> selectSystemByParm(System system);

    /**
     * 获取被关注列表
     * @param system
     * @return
     */
    List<Map> findMarkedUsers(System system);
}