package com.clt.intel.dao;

import com.clt.intel.bean.UserSystem;
import org.springframework.stereotype.Repository;

@Repository("userSystemMapper")
public interface UserSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intel_user_system
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    int insert(UserSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intel_user_system
     *
     * @mbggenerated Wed Jun 15 14:32:14 CST 2016
     */
    int insertSelective(UserSystem record);
}